name: Update README

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  update-readme:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Use the latest Python 3.x version

      # Install dependencies (if any)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Add any dependencies your script requires here
          # pip install -r requirements.txt

      # Run the Python script
      - name: Run generate_index.py
        run: python generate_index.py

      # Commit and push changes (if the script modifies files)
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automatically update README.md"
          git push
